trigger:
  tags:
    include:
      - refs/tags/dify-api-*
  branches:
    include:
      - 1.2-patch
      - '*-patch'

pool: 'Default'

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)
#jobs前还可以包一层 stages:
#   - stage: addGlobalVariables
#     jobs:
jobs:
  - job: BuildCNImage
    displayName: "Build and push aep cn image"
    steps:
      - script: |
          echo "##vso[build.updatebuildnumber]$(Build.SourceBranchName)"
        displayName: 'Change build number format'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

      - task: Docker@2
        inputs:
          containerRegistry: 'artimom.mom.works'
          repository: 'docker-atcraft-dev/lyfe'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: '$(Build.BuildNumber)'
        displayName: "docker build docker-atcraft-dev/lyfe"

      - task: Docker@2
        displayName: login artimom.mom.works
        inputs:
          containerRegistry: artimom.mom.works
          command: login

      - task: Docker@2
        inputs:
          containerRegistry: 'artimom.mom.works'
          repository: 'docker-atcraft-dev/lyfe'
          command: 'push'
          tags: '$(Build.BuildNumber)'
        displayName: "docker push artimom.mom.works/docker-atcraft-dev/lyfe"
      
      - script: |
          docker rmi artimom.mom.works/docker-atcraft-dev/lyfe:$(Build.BuildNumber)
        displayName: 'rm image'

  - job: BuildEUImage
    displayName: "Build and push aep eu image"
    steps:
      - script: |
          echo "##vso[build.updatebuildnumber]$(Build.SourceBranchName)"
        displayName: 'Change build number format'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

      - task: Docker@2
        inputs:
          containerRegistry: 'artimom.mom.works'
          repository: 'docker-atcraft-dev/lyfe'
          command: 'build'
          Dockerfile: '**/Dockerfile.eu'
          tags: '$(Build.BuildNumber)-eu'
        displayName: "docker build docker-atcraft-dev/lyfe eu"

      - task: Docker@2
        displayName: login artimom.mom.works
        inputs:
          containerRegistry: artimom.mom.works
          command: login

      - task: Docker@2
        inputs:
          containerRegistry: 'artimom.mom.works'
          repository: 'docker-atcraft-dev/lyfe'
          command: 'push'
          tags: '$(Build.BuildNumber)-eu'
        displayName: "docker push artimom.mom.works/docker-atcraft-dev/lyfe eu"
      
      - script: |
          docker rmi artimom.mom.works/docker-atcraft-dev/lyfe:$(Build.BuildNumber)-eu
        displayName: 'rm image'
